# Generated by Django 3.0 on 2023-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio_venta', models.FloatField()),
                ('precio_descontado', models.FloatField()),
                ('descripcion', models.TextField()),
                ('composicion', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('categoria', models.CharField(choices=[('IP', 'Iphone'), ('LN', 'Lenovo'), ('TB', 'Ipad'), ('LP', 'Laptop asus'), ('MD', 'Mando'), ('CS', 'Consola-ps5')], max_length=2)),
                ('producto_imagen', models.ImageField(upload_to='product')),
            ],
        ),
    ]
