# Generated by Django 3.0 on 2023-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('tl', 'Telefono'), ('tb', 'Tablet'), ('lp', 'Laptop'), ('ac', 'Accesorios'), ('md', 'Mando'), ('cs', 'Consola')], max_length=2),
        ),
    ]
