# Generated by Django 3.0 on 2023-03-16 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20230315_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=50)),
                ('móvil', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('estado', models.CharField(choices=[('AZU', 'Azuay'), ('BOL', 'Bolívar'), ('CAN', 'Cañar'), ('CAR', 'Carchi'), ('CHI', 'Chimborazo'), ('COT', 'Cotopaxi'), ('EOR', 'El Oro'), ('ESM', 'Esmeraldas'), ('GAL', 'Galápagos'), ('GUA', 'Guayas'), ('IMB', 'Imbabura'), ('LOJ', 'Loja'), ('LRO', 'Los Ríos'), ('MAN', 'Manabí'), ('MSA', 'Morona Santiago'), ('NAP', 'Napo'), ('ORE', 'Orellana'), ('PAS', 'Pastaza'), ('PIC', 'Pichincha'), ('SUC', 'Sucumbíos'), ('TUN', 'Tungurahua'), ('ZCH', 'Zamora Chinchipe')], max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
